<?php

namespace Container1UUOcgr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZIrs5rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zIrs5r_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zIrs5r_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dompdfService' => ['privates', 'App\\Services\\DompdfService', 'getDompdfServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'dompdfService' => 'App\\Services\\DompdfService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
