<?php

namespace Container1UUOcgr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K0V8BeGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k0V8BeG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k0V8BeG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'garant' => ['privates', '.errored..service_locator.k0V8BeG.App\\Entity\\GarantFinancier', NULL, 'Cannot autowire service ".service_locator.k0V8BeG": it needs an instance of "App\\Entity\\GarantFinancier" but this type has been excluded in "config/services.yaml".'],
            'garantFinancierRepository' => ['privates', 'App\\Repository\\GarantFinancierRepository', 'getGarantFinancierRepositoryService', true],
        ], [
            'garant' => 'App\\Entity\\GarantFinancier',
            'garantFinancierRepository' => 'App\\Repository\\GarantFinancierRepository',
        ]);
    }
}
