<?php

namespace ContainerI5NmwMu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OoWztaGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ooWztaG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ooWztaG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergement' => ['privates', '.errored..service_locator.ooWztaG.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.ooWztaG": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded in "config/services.yaml".'],
            'hebergementRepository' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', true],
        ], [
            'hebergement' => 'App\\Entity\\Hebergement',
            'hebergementRepository' => 'App\\Repository\\HebergementRepository',
        ]);
    }
}
