<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCknwBri\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCknwBri/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCknwBri.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCknwBri\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCknwBri\App_KernelProdContainer([
    'container.build_hash' => 'CknwBri',
    'container.build_id' => '0456fdb7',
    'container.build_time' => 1708201700,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCknwBri');
