<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJOMCPmX\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJOMCPmX/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJOMCPmX.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJOMCPmX\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJOMCPmX\App_KernelProdContainer([
    'container.build_hash' => 'JOMCPmX',
    'container.build_id' => '417aa9f5',
    'container.build_time' => 1708037527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJOMCPmX');
