<?php

namespace ContainerJOMCPmX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGarantFinancierRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GarantFinancierRepository' shared autowired service.
     *
     * @return \App\Repository\GarantFinancierRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GarantFinancierRepository'] = new \App\Repository\GarantFinancierRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
