<?php

namespace ContainerJOMCPmX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicMessageRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PublicMessageRepository' shared autowired service.
     *
     * @return \App\Repository\PublicMessageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PublicMessageRepository'] = new \App\Repository\PublicMessageRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
