<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'NumeroIdentificationNational' => [parent::class, 'NumeroIdentificationNational', null],
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null],
        "\0".parent::class."\0".'dateOfBirth' => [parent::class, 'dateOfBirth', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'filiary' => [parent::class, 'filiary', null],
        "\0".parent::class."\0".'garantFinancier' => [parent::class, 'garantFinancier', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'school_level' => [parent::class, 'school_level', null],
        'NumeroIdentificationNational' => [parent::class, 'NumeroIdentificationNational', null],
        'avatar' => [parent::class, 'avatar', null],
        'dateOfBirth' => [parent::class, 'dateOfBirth', null],
        'email' => [parent::class, 'email', null],
        'filiary' => [parent::class, 'filiary', null],
        'garantFinancier' => [parent::class, 'garantFinancier', null],
        'id' => [parent::class, 'id', null],
        'isVerified' => [parent::class, 'isVerified', null],
        'lastName' => [parent::class, 'lastName', null],
        'name' => [parent::class, 'name', null],
        'password' => [parent::class, 'password', null],
        'phone' => [parent::class, 'phone', null],
        'roles' => [parent::class, 'roles', null],
        'school_level' => [parent::class, 'school_level', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
