<?php

namespace ContainerQxetRmI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JsOusUoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jsOusUo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jsOusUo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergement' => ['privates', '.errored..service_locator.jsOusUo.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.jsOusUo": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded in "config/services.yaml".'],
            'hebergementRepository' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'hebergement' => 'App\\Entity\\Hebergement',
            'hebergementRepository' => 'App\\Repository\\HebergementRepository',
            'mailer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
