<?php

namespace ContainerXTKju7z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.awqL4yC.App\Entity\Dossier' shared service.
     *
     * @return \App\Entity\Dossier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.awqL4yC": it needs an instance of "App\\Entity\\Dossier" but this type has been excluded in "config/services.yaml".');
    }
}
