<?php

namespace ContainerXTKju7z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGarantFinancierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Uz253Yf.App\Entity\GarantFinancier' shared service.
     *
     * @return \App\Entity\GarantFinancier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Uz253Yf": it needs an instance of "App\\Entity\\GarantFinancier" but this type has been excluded in "config/services.yaml".');
    }
}
