<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2bq6ZcY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2bq6ZcY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2bq6ZcY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2bq6ZcY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2bq6ZcY\App_KernelDevDebugContainer([
    'container.build_hash' => '2bq6ZcY',
    'container.build_id' => '7e5f1002',
    'container.build_time' => 1709000224,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2bq6ZcY');
