<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTKju7z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTKju7z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTKju7z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTKju7z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXTKju7z\App_KernelDevDebugContainer([
    'container.build_hash' => 'XTKju7z',
    'container.build_id' => 'c4b45735',
    'container.build_time' => 1714850418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTKju7z');
