<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GarantFinancier extends \App\Entity\GarantFinancier implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateDemande' => [parent::class, 'dateDemande', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'informations' => [parent::class, 'informations', null],
        "\0".parent::class."\0".'last_update' => [parent::class, 'last_update', null],
        "\0".parent::class."\0".'pathAdmissionFile' => [parent::class, 'pathAdmissionFile', null],
        "\0".parent::class."\0".'pathGarantFile' => [parent::class, 'pathGarantFile', null],
        "\0".parent::class."\0".'pathPassport' => [parent::class, 'pathPassport', null],
        "\0".parent::class."\0".'pays' => [parent::class, 'pays', null],
        "\0".parent::class."\0".'statutDemande' => [parent::class, 'statutDemande', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'villeEtude' => [parent::class, 'villeEtude', null],
        'dateDemande' => [parent::class, 'dateDemande', null],
        'id' => [parent::class, 'id', null],
        'informations' => [parent::class, 'informations', null],
        'last_update' => [parent::class, 'last_update', null],
        'pathAdmissionFile' => [parent::class, 'pathAdmissionFile', null],
        'pathGarantFile' => [parent::class, 'pathGarantFile', null],
        'pathPassport' => [parent::class, 'pathPassport', null],
        'pays' => [parent::class, 'pays', null],
        'statutDemande' => [parent::class, 'statutDemande', null],
        'user' => [parent::class, 'user', null],
        'villeEtude' => [parent::class, 'villeEtude', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
