<?php

namespace Container2bq6ZcY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ExportController' shared autowired service.
     *
     * @return \App\Controller\ExportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ExportController.php';

        $container->services['App\\Controller\\ExportController'] = $instance = new \App\Controller\ExportController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ExportController', $container));

        return $instance;
    }
}
